# Generated by Django 5.1.3 on 2024-11-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0002_empleado_remove_helado_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empleado',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='helado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
