# Generated by Django 5.1.3 on 2024-11-27 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0004_cliente_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='PedidoEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidosemp', to='helados.empleado')),
                ('producto', models.ManyToManyField(related_name='pedidosemp', to='helados.helado')),
            ],
        ),
    ]
