# Generated by Django 5.1.3 on 2024-11-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0005_alter_cliente_nit_alter_pedido_codigo_pedidoempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='horaTrabajada',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ManyToManyField(related_name='pedidosh', to='helados.helado'),
        ),
        migrations.AlterField(
            model_name='pedidoempleado',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
