# Generated by Django 5.1.3 on 2024-11-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0006_empleado_horatrabajada_alter_pedido_producto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='horaTrabajada',
        ),
        migrations.AddField(
            model_name='pedidoempleado',
            name='horaTrabajada',
            field=models.IntegerField(default=0),
        ),
    ]
