# Generated by Django 5.1.3 on 2024-11-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0007_remove_empleado_horatrabajada_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoempleado',
            name='horaTrabajada',
        ),
        migrations.AlterField(
            model_name='pedidoempleado',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
